name: CI Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      - name: Login to the DH
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_UN }}
          password: ${{ secrets.DH_PAT }}
      - name: Build Image
        run: docker image build -t ${{secrets.DH_UN}}/app:latest .
      - name: Push Docker Image on DH
        run: docker push ${{secrets.DH_UN}}/app:latest
        


